name: CI/CD Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Set up Java (if required)
        uses: actions/setup-java@v1
        with:
          java-version: '11'

      - name: Build Project
        run: |
          # Replace with your project's build command.
          ./gradlew build

      - name: Run Tests
        run: |
          # Replace with your project's test command.
          ./gradlew test

      - name: Run SonarQube Analysis
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: |
          sonar-scanner \
            -Dsonar.projectKey=devsecops-pipeline \
            -Dsonar.sources=. \
            -Dsonar.host.url=http://localhost:9000 \
            -Dsonar.login=$SONAR_TOKEN
